// parser generated by Antlr4Rust: "https://github.com/rrevenantt/antlr4rust"

use antlr_rust::{common_token_stream::CommonTokenStream, tree::ParseTree, InputStream};

use self::{mathlexer::mathLexer, mathparser::mathParser};


mod mathlexer;
mod mathparser;
mod mathlistener;

#[should_panic]
#[test]
fn test_parser() {
    let lexer = mathLexer::new(InputStream::new("(4 + 8) * 9 + 7".into()));

    let token_source = CommonTokenStream::new(lexer);
    let mut parser = mathParser::new(token_source);

    let result = parser.expr().expect("parsing failed");
    assert_eq!(result.to_string_tree(&*parser), "");
}